title: CGS Astronomy Club
author:
  name: CGS Astronomy Club
  email:
    - alex.maksimov@cgs.act.edu.au
    - callum.bennett@cgs.act.edu.au

description: >
  We invite cool people to talk about their achievements in astronomy and explore the night sky ourselves. Brought to you by Julie Davies, Alex Monro, Callum Bennett, Jessica Li and Alex Maksimov.

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  skin: dark
  
header_pages:
  - stream.md
  - about.md
